feat(argo): add argo cronjob for git repo

diff --git a/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml b/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
--- a/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
+++ b/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
@@ -4,24 +4,26 @@ kind: CronWorkflow
 metadata:
   name: list-repos-with-topic
 spec:
-  schedule: "*/1 * * * *"
+  schedule: '*/1 * * * *'
+  serviceAccountName: argo-resources
   workflowSpec:
     entrypoint: list-repos
     templates:
-    - name: list-repos
-      container:
-        image: alpine:latest
-        command: [sh, -c]
-        args:
-        - |
-          apk add --no-cache curl jq
-          USER="gperreymond"
-          TOPIC="argo-workflow"
-          URL="https://api.github.com/users/$USER/repos"
-          response=$(curl -s "$URL")
-          if [ $? -ne 0 ]; then
-            echo "Error making request to the GitHub API."
-            exit 1
-          fi
-          echo "List of $USER's repositories with the topic '$TOPIC':"
-          echo "$response" | jq -r '.[] | select(.topics[]? == "'$TOPIC'") | .name'
+      - name: list-repos
+
+        container:
+          image: alpine:latest
+          command: [sh, -c]
+          args:
+          - |
+              apk add --no-cache curl jq
+              USER="gperreymond"
+              TOPIC="argo-workflow"
+              URL="https://api.github.com/users/$USER/repos"
+              response=$(curl -s "$URL")
+              if [ $? -ne 0 ]; then
+                echo "Error making request to the GitHub API."
+                exit 1
+              fi
+              echo "List of $USER's repositories with the topic '$TOPIC':"
+              echo "$response" | jq -r '.[] | select(.topics[]? == "'$TOPIC'") | .name'
