feat(argo): cronjob git repos output

diff --git a/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml b/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
--- a/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
+++ b/charts/remote-applications/argo-resources/templates/workflows/list-repos-with-topic.yaml
@@ -14,18 +14,18 @@ spec:
           image: alpine:latest
           command: [sh, -c]
           args:
-          - |
-            apk add --no-cache curl jq
-            USER="gperreymond"
-            TOPIC="argo-workflow"
-            URL="https://api.github.com/users/$USER/repos"
-            response=$(curl -s "$URL")
-            if [ $? -ne 0 ]; then
-              echo "Error making request to the GitHub API."
-              exit 1
-            fi
-            echo "List of $USER's repositories with the topic '$TOPIC':"
-            echo "$response" | jq -r '.[] | select(.topics[]? == "'$TOPIC'") | .name' > /tmp/repos.txt
+            - |
+              apk add --no-cache curl jq
+              USER="gperreymond"
+              TOPIC="argo-workflow"
+              URL="https://api.github.com/users/$USER/repos"
+              response=$(curl -s "$URL")
+              if [ $? -ne 0 ]; then
+                echo "Error making request to the GitHub API."
+                exit 1
+              fi
+              echo "List of $USER's repositories with the topic '$TOPIC':"
+              echo "$response" | jq -r '.[] | select(.topics[]? == "'$TOPIC'") | .name' > /tmp/repos.txt
         outputs:
           parameters:
             - name: repos
@@ -40,23 +40,23 @@ spec:
           image: alpine:latest
           command: [sh, -c]
           args:
-          - |
-            apk add --no-cache curl jq
-            USER="gperreymond"
-            REPO="{{ `{{inputs.parameters.repo}}` }}"
-            URL="https://api.github.com/repos/$USER/$REPO/contents/.argo-workflow.yaml"
-            response=$(curl -s "$URL")
-            if [ $? -ne 0 ]; then
-              echo "Error making request to the GitHub API."
-              exit 1
-            fi
-            if echo "$response" | jq -e '.name == ".argo-workflow.yaml"' > /dev/null; then
-              echo "File .argo-workflow.yaml exists in repository $REPO."
-            else
-              echo "File .argo-workflow.yaml does not exist in repository $REPO."
-            fi
+            - |
+              apk add --no-cache curl jq
+              USER="gperreymond"
+              REPO="{{ `{{inputs.parameters.repo}}` }}"
+              URL="https://api.github.com/repos/$USER/$REPO/contents/.argo-workflow.yaml"
+              response=$(curl -s "$URL")
+              if [ $? -ne 0 ]; then
+                echo "Error making request to the GitHub API."
+                exit 1
+              fi
+              if echo "$response" | jq -e '.name == ".argo-workflow.yaml"' > /dev/null; then
+                echo "File .argo-workflow.yaml exists in repository $REPO."
+              else
+                echo "File .argo-workflow.yaml does not exist in repository $REPO."
+              fi
       - name: check-all-repos
-          steps:
+        steps:
           - - name: list-repos
               template: list-repos
           - - name: check-file-in-repos
